// Generated by CoffeeScript 1.10.0

/*
 * Récupère la signature alphabétique d'un texte
 *
 * @module sign
 */


/*
 * Tri alphabétique.
 * On souhaite normaliser la séquence.
 *
 * @method alphaSort
 *
 * @private
 */

(function() {
  var alphaSort, sign;

  alphaSort = function(prev, next) {
    return prev.localeCompare(next);
  };


  /*
   * Construit la signature d'un mot.
   *
   * @method sign
   * @param {String} txt Chaîne de caractère dont on veut obtenir la signature.
   * @return {Object} Un object qui dénombre les occurences de chaque lettre.
   */

  sign = function(txt) {
    var incrementOccurrence, signature;
    signature = {};
    incrementOccurrence = function(char) {
      var empty, increment;
      empty = 0;
      increment = 1;
      return signature[char] = (signature[char] || empty) + increment;
    };
    txt.replace(/\s*/g, '').split('').sort(alphaSort).forEach(incrementOccurrence);
    return signature;
  };

  module.exports = sign;

}).call(this);
